name: flutter_desktop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.1
  provider: ^6.0.1
  system_theme: ^1.0.1
  bitsdojo_window: ^0.1.1+1
  window_manager: ^0.1.7
  flutter_acrylic: ^1.0.0+1
  url_strategy: ^0.2.0
  url_launcher: ^6.0.15
  clipboard: ^0.1.3
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
